stages:
  - name: test
  - name: deploy
    if: branch == production

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - lts/*
      install: "npm install"
      script:
        - npm run test
        
    - stage: deploy
      language: node_js
      node_js: "12"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_TOKEN
        skip_cleanup: true
        on:
          tags: true